name: Publish to OCI registries

on:
  release:
    types:
      - released
  workflow_dispatch:

env:
  QUAY_NAMESPACE: atakiya
  QUAY_REPO: vintagestory-server
  GHCR_REPO: ${{ github.repository_owner }}/vintagestory-server

jobs:
  github:
    name: Build & Push image to GHCR
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set metadata for GHCR image
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ env.GHCR_REPO }}

      - name: Log in to GitHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  quay:
    name: Build & Push image to Quay.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set metadata for Quay.io image
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: quay.io/${{ env.QUAY_NAMESPACE }}/${{ env.QUAY_REPO }}

      - name: Log in to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
